### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by fabaff** [projectdiscovery/fdmax#3]
Please add a license statement and include a LICENSE file in the repo.

This is a dependency of naabu and naabu is available in the Fedora Package Collection. To provide an update to the latest naabu release tfdmax needs to in the Package Collection too and to do that a license is required.

Thanks

**Comment by ehsandeep** [comment]
Hi @fabaff, 

Thank you for pointing this out, we just added it here https://github.com/projectdiscovery/fdmax/commit/5240e7961ba00ff79248d950fe1035a693f415ea

**Comment by fabaff** [comment]
@bauthard, thank you.
