### ISSUE TITLE
Add support to all *nix compatible Operating Systems

### ISSUE THREAD

**Issue by vzamanillo** [projectdiscovery/fdmax#5]
Related to https://github.com/projectdiscovery/subfinder/issues/334

`fdmax` does not actually support some unix based operating systems as `openbsd`, `freebsd`, `solaris`... etc

I am not sure if `//+build unix` is currently supported on go https://github.com/golang/go/issues/20322, and if the go tool recognize `_unix` as a file suffix, but we can use an inverse constraint to detect non windows operating systems `//+build !windows`

**Comment by yurivict** [comment]
The ```subfinder``` project fails on FreeBSD because of this issue: https://github.com/projectdiscovery/subfinder/issues/334
